// Preset question banks for the BRUH review game.
//
// Every question was authored per topic and then independently re-solved from
// scratch by two separate checkers; only items both checkers agreed with were
// kept. All 240 survived with no corrections. Sourced 2026-07; re-verify before
// changing an answer.
//
// "Mixed Review" is the original Period 4 deck, carried over from the Canva
// version so the first game is the one the class already knows.

export interface BruhQuestion {
  n: number;
  topic: string;
  q: string;
  a: string;
}

export interface BruhPreset {
  key: string;
  label: string;
  questions: BruhQuestion[];
}

export const BRUH_PRESETS: BruhPreset[] = [
  {
    key: "mixed",
    label: "Mixed Review",
    questions: [
      { n: 1, topic: "Solve for x", q: "2x = 16", a: "8" },
      { n: 2, topic: "Geography", q: "What is the largest ocean in the world?", a: "Pacific Ocean" },
      { n: 3, topic: "Simplify", q: "4y - 12 + 9", a: "4y - 3" },
      { n: 4, topic: "Money", q: "A concert ticket costs $45. You have $200. How many tickets can you buy?", a: "4" },
      { n: 5, topic: "Unit rate", q: "A machine makes 45 parts in 15 minutes. How many parts in 1 hour?", a: "180" },
      { n: 6, topic: "Write and solve", q: "A number multiplied by 4 and then increased by 7 equals 31. Solve it.", a: "6" },
      { n: 7, topic: "Inequality", q: "To ride the roller coaster you must be at least 48 inches tall. Write it using h.", a: "h >= 48" },
      { n: 8, topic: "Solve for x", q: "3x + 6 = 9", a: "1" },
      { n: 9, topic: "Area", q: "A rectangle has an area of 72 square feet. One side is 8 ft. Find the missing side.", a: "9" },
      { n: 10, topic: "Percent", q: "You paid $38 total after a $5 discount and $3 tax. What was the original price?", a: "40" },
      { n: 11, topic: "Expressions", q: "A streaming service charges $12 per month plus $3 per movie. Cost for 7 movies?", a: "33" },
      { n: 12, topic: "Ratio", q: "A class has a ratio of 3:5 boys to girls. 24 students total. How many boys?", a: "9" },
      { n: 13, topic: "Solve for p", q: "2p + 6 = 8", a: "1" },
      { n: 14, topic: "Inequality", q: "A student earns $12 per hour and wants at least $90. How many hours?", a: "8" },
      { n: 15, topic: "Percent", q: "A store takes 20% off a $60 jacket. What is the final price?", a: "48" },
      { n: 16, topic: "Data", q: "Scores: 60, 65, 70, 75, 100. Which is the better measure, mean or median?", a: "Median" },
      { n: 17, topic: "Combine terms", q: "8w + 10 + 2w - 4", a: "10w + 6" },
      { n: 18, topic: "Area", q: "A rectangular garden is 8 ft long and 5 ft wide. Find the area.", a: "40" },
      { n: 19, topic: "Unit rate", q: "A phone plan costs $15 plus $5 per GB. The total bill was $40. How many GB?", a: "5" },
      { n: 20, topic: "Write and solve", q: "You have $32 after spending $8. How much did you start with?", a: "40" },
      { n: 21, topic: "Expressions", q: "A gym charges $10 per visit plus a $25 fee. Find the cost after 6 visits.", a: "85" },
      { n: 22, topic: "Percent", q: "A video game costs $40. The price increases by 25%. What is the new price?", a: "50" },
      { n: 23, topic: "Combine terms", q: "9r + 6s + 20 - 4r - 3s - 5", a: "5r + 3s + 15" },
      { n: 24, topic: "Percent", q: "What is 25% of 90?", a: "22.5" },
      { n: 25, topic: "Percent", q: "A student scored 84% on a test with 50 questions. How many were correct?", a: "42" },
      { n: 26, topic: "Unit rate", q: "A car travels 180 miles in 3 hours. What is the unit rate?", a: "60" },
      { n: 27, topic: "Solve for x", q: "5x - 4 = 26", a: "6" },
      { n: 28, topic: "Ratio", q: "4 pens cost $6. What do 10 pens cost?", a: "15" },
      { n: 29, topic: "Area", q: "A triangle has a base of 12 cm and a height of 5 cm. Find the area.", a: "30" },
      { n: 30, topic: "Percent", q: "15 is what percent of 60?", a: "25" },
    ],
  },
  {
    key: "expressions",
    label: "Expressions",
    questions: [
      { n: 1, topic: "Evaluating", q: "Evaluate 3x + 7 when x = 5.", a: "22" },
      { n: 2, topic: "Evaluating", q: "Evaluate 4n - 9 when n = 6.", a: "15" },
      { n: 3, topic: "Evaluating", q: "Evaluate x/4 + 10 when x = 32.", a: "18" },
      { n: 4, topic: "Parentheses", q: "Evaluate 2(y + 5) when y = 7.", a: "24" },
      { n: 5, topic: "Two variables", q: "Evaluate 5a - 2b when a = 4 and b = 3.", a: "14" },
      { n: 6, topic: "Exponents", q: "Evaluate x^2 + 1 when x = 9.", a: "82" },
      { n: 7, topic: "Like terms", q: "Simplify by combining like terms: 4x + 7 + 3x - 2", a: "7x + 5" },
      { n: 8, topic: "Like terms", q: "Simplify by combining like terms: 9y - 4y + 6", a: "5y + 6" },
      { n: 9, topic: "Like terms", q: "Simplify by combining like terms: 5a + 2b + 3a + 4b", a: "8a + 6b" },
      { n: 10, topic: "Like terms", q: "Simplify by combining like terms: 12n + 5 - 7n - 5", a: "5n" },
      { n: 11, topic: "Coefficients", q: "What is the coefficient of x in the expression 8x + 3?", a: "8" },
      { n: 12, topic: "Constants", q: "What is the constant in the expression 4y + 9?", a: "9" },
      { n: 13, topic: "Counting terms", q: "How many terms are in the expression 3x + 2y - 7?", a: "3" },
      { n: 14, topic: "Coefficients", q: "What is the coefficient of y in the expression y + 15?", a: "1" },
      { n: 15, topic: "Writing expressions", q: "Write an expression for seven more than a number n.", a: "n + 7" },
      { n: 16, topic: "Writing expressions", q: "Write an expression for the product of 6 and a number x.", a: "6x" },
      { n: 17, topic: "Writing expressions", q: "Write an expression for a number y divided by 5.", a: "y/5" },
      { n: 18, topic: "Writing expressions", q: "Write an expression for 9 less than twice a number n.", a: "2n - 9" },
      { n: 19, topic: "Writing expressions", q: "Movie tickets cost 8 dollars each. Write an expression for the cost of t tickets.", a: "8t" },
      { n: 20, topic: "Writing expressions", q: "Jo has s stickers. Mia has 5 more stickers than Jo. Write an expression for Mia's stickers.", a: "s + 5" },
      { n: 21, topic: "Two-step", q: "A gym charges 25 dollars to join plus 4 dollars per class. Write an expression for the cost of c classes.", a: "4c + 25" },
      { n: 22, topic: "Evaluating", q: "A plumber charges 50 dollars plus 30 dollars per hour. How much does a 3-hour job cost?", a: "140" },
      { n: 23, topic: "Two-step", q: "Each pizza has 8 slices and there are 3 extra slices. Write an expression for total slices with p pizzas.", a: "8p + 3" },
      { n: 24, topic: "Evaluating", q: "A rental car costs 40 + 0.25m dollars for m miles. What is the cost for 120 miles?", a: "70" },
      { n: 25, topic: "Writing expressions", q: "Sam buys n notebooks at 3 dollars each and pays with a 20-dollar bill. Write an expression for his change.", a: "20 - 3n" },
      { n: 26, topic: "Like terms", q: "Ava has 3x + 4 marbles and Ben has 2x + 6 marbles. Write a simplified expression for their total.", a: "5x + 10" },
      { n: 27, topic: "Perimeter", q: "A rectangle has length x and width 4. Write a simplified expression for its perimeter.", a: "2x + 8" },
      { n: 28, topic: "Writing expressions", q: "The temperature is 70 degrees and drops 2 degrees per hour. Write an expression for it after h hours.", a: "70 - 2h" },
      { n: 29, topic: "Evaluating", q: "Lia earns 9 dollars per hour babysitting. Use the expression 9h to find her pay for 4 hours.", a: "36" },
      { n: 30, topic: "Two-step", q: "A bag of apples weighs 3 pounds. Write an expression for the weight of b bags plus a 2-pound box.", a: "3b + 2" },
    ],
  },
  {
    key: "equations",
    label: "Equations",
    questions: [
      { n: 1, topic: "One-step add", q: "Solve for x: x + 14 = 32", a: "18" },
      { n: 2, topic: "One-step subtract", q: "Solve for n: n - 27 = 45", a: "72" },
      { n: 3, topic: "One-step multiply", q: "Solve for y: 7y = 91", a: "13" },
      { n: 4, topic: "One-step divide", q: "Solve for m: m/8 = 12", a: "96" },
      { n: 5, topic: "Decimal one-step", q: "Solve for x: x + 5.6 = 9.2", a: "3.6" },
      { n: 6, topic: "Fraction coefficient", q: "Solve for n: (3/4)n = 18", a: "24" },
      { n: 7, topic: "Decimal one-step", q: "Solve for w: w - 3.5 = 10.8", a: "14.3" },
      { n: 8, topic: "Decimal answer", q: "Solve for x: 12x = 30", a: "2.5" },
      { n: 9, topic: "Fraction one-step", q: "Solve for x: x + 2/3 = 5/6", a: "1/6" },
      { n: 10, topic: "Two-step", q: "Solve for x: 2x + 7 = 21", a: "7" },
      { n: 11, topic: "Two-step", q: "Solve for n: 3n - 5 = 19", a: "8" },
      { n: 12, topic: "Two-step", q: "Solve for y: 5y + 9 = 54", a: "9" },
      { n: 13, topic: "Two-step divide", q: "Solve for x: x/4 + 3 = 10", a: "28" },
      { n: 14, topic: "Reversed two-step", q: "Solve for m: 34 = 4m - 6", a: "10" },
      { n: 15, topic: "Two-step", q: "Solve for x: 6x - 4 = 32", a: "6" },
      { n: 16, topic: "Two-step divide", q: "Solve for n: n/5 - 2 = 7", a: "45" },
      { n: 17, topic: "Two-step", q: "Solve for x: 10 - 2x = 4", a: "3" },
      { n: 18, topic: "Decimal two-step", q: "Solve for x: 0.5x + 1.5 = 7", a: "11" },
      { n: 19, topic: "One-step word", q: "Ava read 48 pages, which is 15 more than Ben read. How many pages did Ben read?", a: "33" },
      { n: 20, topic: "Two-step word", q: "A gym charges $25 to join plus $8 per month. Malik paid $89 in all. How many months did he pay for?", a: "8" },
      { n: 21, topic: "One-step word", q: "Four friends split a dinner bill equally and each pays $6.75. What was the total bill in dollars?", a: "27" },
      { n: 22, topic: "Two-step word", q: "A taxi ride costs $3 plus $2 per mile. Jade's ride cost $17. How many miles was the ride?", a: "7" },
      { n: 23, topic: "One-step word", q: "Zoe gave away 18 stickers and has 37 left. How many stickers did she start with?", a: "55" },
      { n: 24, topic: "One-step word", q: "Field trip tickets cost $12 each. The class spent $300 in all. How many tickets did they buy?", a: "25" },
      { n: 25, topic: "Two-step word", q: "Kai saves $5 each week and got a $20 gift. He now has $90. For how many weeks has he saved?", a: "14" },
      { n: 26, topic: "Area equation", q: "A rectangle has area 84 sq cm and width 7 cm. Solve 7L = 84 to find the length in cm.", a: "12" },
      { n: 27, topic: "Write and solve", q: "Three times a number decreased by 4 is 26. What is the number?", a: "10" },
      { n: 28, topic: "Two-step word", q: "Leo bought a $9 book and 4 identical pens for $15 total. How much did each pen cost in dollars?", a: "1.5" },
      { n: 29, topic: "One-step word", q: "The temperature dropped 9 degrees to 54 degrees F. What was the starting temperature in degrees?", a: "63" },
      { n: 30, topic: "Two-step word", q: "Priya doubled her score and then earned 10 bonus points to reach 58. What was her original score?", a: "24" },
    ],
  },
  {
    key: "ratios",
    label: "Equivalent Ratios",
    questions: [
      { n: 1, topic: "Scaling up", q: "Complete the equivalent ratio: 3:4 = 12:n. What is n?", a: "16" },
      { n: 2, topic: "Simplest form", q: "Write the ratio 18:24 in simplest form.", a: "3:4" },
      { n: 3, topic: "Recipes", q: "A recipe uses 2 cups of flour for every 3 cups of milk. How many cups of flour go with 9 cups of milk?", a: "6" },
      { n: 4, topic: "Missing value", q: "Find the missing value: 5:8 = n:40.", a: "25" },
      { n: 5, topic: "Simplest form", q: "Write the ratio 40:64 in simplest form.", a: "5:8" },
      { n: 6, topic: "Part-to-whole", q: "A class of 30 students has a boy to girl ratio of 2:3. How many girls are in the class?", a: "18" },
      { n: 7, topic: "Simplest form", q: "Write the ratio 63:81 in simplest form.", a: "7:9" },
      { n: 8, topic: "Ratio tables", q: "In a ratio table for 4:10, what value pairs with 25? Solve 4:10 = n:25.", a: "10" },
      { n: 9, topic: "Rates", q: "Marco reads 45 pages in 3 days. At that rate, how many pages will he read in 7 days?", a: "105" },
      { n: 10, topic: "Equivalence check", q: "Are the ratios 6:9 and 10:15 equivalent? Answer yes or no.", a: "yes" },
      { n: 11, topic: "Equivalence check", q: "Are the ratios 8:12 and 12:20 equivalent? Answer yes or no.", a: "no" },
      { n: 12, topic: "Part-to-whole", q: "The ratio of cats to dogs at a shelter is 3:5. What is the ratio of cats to all animals, in simplest form?", a: "3:8" },
      { n: 13, topic: "Scaling up", q: "A paint mix uses 3 parts red for every 2 parts blue. How many parts red are needed with 8 parts blue?", a: "12" },
      { n: 14, topic: "Missing value", q: "Find the missing value: 7:n = 21:33.", a: "11" },
      { n: 15, topic: "Scale factor", q: "By what factor do you multiply both parts of 3:7 to get 18:42?", a: "6" },
      { n: 16, topic: "Simplest form", q: "Write the ratio 100:250 in simplest form.", a: "2:5" },
      { n: 17, topic: "Scaling up", q: "Trail mix has 5 cups peanuts per 2 cups raisins. How many cups of raisins go with 20 cups of peanuts?", a: "8" },
      { n: 18, topic: "Ratio tables", q: "Six pencils cost 90 cents. Using equivalent ratios, how many cents do 10 pencils cost?", a: "150" },
      { n: 19, topic: "Missing value", q: "Find the missing value: n:12 = 20:48.", a: "5" },
      { n: 20, topic: "Scaling up", q: "Scale the ratio 4:5 up by a factor of 6. What ratio do you get?", a: "24:30" },
      { n: 21, topic: "Part-to-whole", q: "A bag has red and blue marbles in a 4:7 ratio. If there are 44 marbles in all, how many are red?", a: "16" },
      { n: 22, topic: "Simplest form", q: "Write the ratio 9:15 in simplest form.", a: "3:5" },
      { n: 23, topic: "Map scale", q: "On a map, 2 cm represents 5 km. How many km does 9 cm represent?", a: "22.5" },
      { n: 24, topic: "Missing value", q: "Find the missing value: 16:n = 4:11.", a: "44" },
      { n: 25, topic: "Recipes", q: "Juice mix uses 3 cups concentrate per 7 cups water. How many cups of water go with 12 cups of concentrate?", a: "28" },
      { n: 26, topic: "Ratio tables", q: "Find the missing value in the ratio table: 5:9 = 35:n.", a: "63" },
      { n: 27, topic: "Part-to-whole", q: "A library's fiction to nonfiction ratio is 5:3. Out of 64 books, how many are nonfiction?", a: "24" },
      { n: 28, topic: "Simplest form", q: "Write the ratio 48:84 in simplest form.", a: "4:7" },
      { n: 29, topic: "Rates", q: "A car travels 150 miles on 6 gallons of gas. At the same rate, how far in miles can it go on 10 gallons?", a: "250" },
      { n: 30, topic: "Missing value", q: "The ratio 6:x is equivalent to 15:35. What is x?", a: "14" },
    ],
  },
  {
    key: "unitrates",
    label: "Unit Rates",
    questions: [
      { n: 1, topic: "Price per item", q: "A pack of 12 pencils costs $3.36. What is the cost of one pencil in cents?", a: "28" },
      { n: 2, topic: "Speed", q: "A car travels 195 miles in 3 hours. What is its speed in miles per hour?", a: "65" },
      { n: 3, topic: "Per minute", q: "A printer prints 84 pages in 7 minutes. How many pages does it print per minute?", a: "12" },
      { n: 4, topic: "Better buy", q: "Brand A: 8 granola bars for $6.00. Brand B: 5 bars for $4.00. Which brand is the better buy, A or B?", a: "A" },
      { n: 5, topic: "Scaling a rate", q: "Apples cost $4.50 for 3 pounds. At this rate, how much do 8 pounds cost in dollars?", a: "12" },
      { n: 6, topic: "Minutes per mile", q: "A runner jogs 3 miles in 24 minutes. How many minutes does she take per mile?", a: "8" },
      { n: 7, topic: "Per minute", q: "A hose fills 18 gallons in 4 minutes. What is the rate in gallons per minute?", a: "4.5" },
      { n: 8, topic: "Scaling a rate", q: "6 notebooks cost $9. At this rate, what do 10 notebooks cost in dollars?", a: "15" },
      { n: 9, topic: "Speed", q: "A cyclist rides 54 miles in 4.5 hours. What is her speed in miles per hour?", a: "12" },
      { n: 10, topic: "Unit price", q: "Grapes cost $2.25 per pound. How much do 4 pounds of grapes cost in dollars?", a: "9" },
      { n: 11, topic: "Per minute", q: "A heart beats 210 times in 3 minutes. How many beats is that per minute?", a: "70" },
      { n: 12, topic: "Price per ounce", q: "A 64-ounce jug of juice costs $4.80. What is the price per ounce in cents?", a: "7.5" },
      { n: 13, topic: "Speed", q: "A plane flies 2100 miles in 6 hours. What is its average speed in miles per hour?", a: "350" },
      { n: 14, topic: "Per minute", q: "Tina types 270 words in 6 minutes. How many words does she type per minute?", a: "45" },
      { n: 15, topic: "Scaling a rate", q: "A recipe uses 3 cups of flour to make 24 cookies. How many cups are needed for 40 cookies?", a: "5" },
      { n: 16, topic: "Two-step", q: "Gas costs $3.60 per gallon. How many gallons can you buy with exactly $27?", a: "7.5" },
      { n: 17, topic: "Better buy", q: "Store X sells 3 shirts for $21. Store Y sells 5 shirts for $30. Which store is cheaper per shirt, X or Y?", a: "Y" },
      { n: 18, topic: "Per minute", q: "A snail crawls 15 inches in 6 minutes. How many inches does it crawl per minute?", a: "2.5" },
      { n: 19, topic: "Hourly wage", q: "Ella earns $54 for 8 hours of babysitting. How much does she earn per hour in dollars?", a: "6.75" },
      { n: 20, topic: "Miles per gallon", q: "A car uses 12 gallons of gas to travel 324 miles. How many miles per gallon is that?", a: "27" },
      { n: 21, topic: "Scaling a rate", q: "A machine makes 45 toys per hour. How many toys does it make in 4 hours?", a: "180" },
      { n: 22, topic: "Distance", q: "A train travels at 80 miles per hour. How many miles does it travel in 2.5 hours?", a: "200" },
      { n: 23, topic: "Two-step", q: "Copies cost 6 cents each. How much do 250 copies cost in dollars?", a: "15" },
      { n: 24, topic: "Price per item", q: "9 oranges cost $5.40. What is the cost of one orange in cents?", a: "60" },
      { n: 25, topic: "Better buy", q: "A 12-pack of soda costs $5.40 and a 20-pack costs $8.00. How many cents cheaper per can is the 20-pack?", a: "5" },
      { n: 26, topic: "Scaling a rate", q: "Mia reads 36 pages in 45 minutes. At this rate, how many pages can she read in 60 minutes?", a: "48" },
      { n: 27, topic: "Per minute", q: "A pump moves 7.5 liters of water per minute. How many liters does it move in 12 minutes?", a: "90" },
      { n: 28, topic: "Two-step", q: "It takes 6 hours to paint 4 walls. At this rate, how many hours will 10 walls take?", a: "15" },
      { n: 29, topic: "Fraction rate", q: "A turtle walks 1/2 mile in 1/4 hour. What is its speed in miles per hour?", a: "2" },
      { n: 30, topic: "Price per item", q: "A group of 12 friends pays $156 total for tickets. How much is each ticket in dollars?", a: "13" },
    ],
  },
  {
    key: "percents",
    label: "Percents",
    questions: [
      { n: 1, topic: "Percent of number", q: "What is 25% of 80?", a: "20" },
      { n: 2, topic: "Percent of number", q: "What is 10% of 340?", a: "34" },
      { n: 3, topic: "What percent", q: "What percent of 50 is 13?", a: "26" },
      { n: 4, topic: "Discount", q: "A $40 shirt is on sale for 25% off. What is the sale price in dollars?", a: "30" },
      { n: 5, topic: "Percent of number", q: "What is 50% of 96?", a: "48" },
      { n: 6, topic: "Find the whole", q: "30% of a number is 18. What is the number?", a: "60" },
      { n: 7, topic: "Tax", q: "A $60 video game has 8% sales tax added. What is the total cost in dollars?", a: "64.80" },
      { n: 8, topic: "Percent of number", q: "What is 75% of 44?", a: "33" },
      { n: 9, topic: "What percent", q: "18 is what percent of 120?", a: "15" },
      { n: 10, topic: "Percent of number", q: "A class of 40 students is 45% boys. How many boys are in the class?", a: "18" },
      { n: 11, topic: "Percent of number", q: "What is 20% of 65?", a: "13" },
      { n: 12, topic: "Find the whole", q: "25% of what number is 17?", a: "68" },
      { n: 13, topic: "Discount", q: "Jeans priced at $50 are 30% off. What is the sale price in dollars?", a: "35" },
      { n: 14, topic: "Percent of number", q: "What is 15% of 60?", a: "9" },
      { n: 15, topic: "What percent", q: "Maya answered 17 out of 20 quiz questions correctly. What percent did she get right?", a: "85" },
      { n: 16, topic: "Find the whole", q: "14 is 40% of what number?", a: "35" },
      { n: 17, topic: "Percent of number", q: "What is 5% of 120?", a: "6" },
      { n: 18, topic: "Tip", q: "A restaurant meal costs $25. How many dollars is a 20% tip?", a: "5" },
      { n: 19, topic: "Percent of number", q: "What is 40% of 90?", a: "36" },
      { n: 20, topic: "Find the whole", q: "15 students walk to school. That is 30% of the class. How many students are in the class?", a: "50" },
      { n: 21, topic: "What percent", q: "What percent of 200 is 46?", a: "23" },
      { n: 22, topic: "Discount", q: "A backpack costs $32. A 15% discount saves you how many dollars?", a: "4.80" },
      { n: 23, topic: "Percent of number", q: "What is 150% of 30?", a: "45" },
      { n: 24, topic: "Find the whole", q: "90% of what number is 63?", a: "70" },
      { n: 25, topic: "What percent", q: "At the park, 12 of the 30 dogs are puppies. What percent of the dogs are puppies?", a: "40" },
      { n: 26, topic: "Percent of number", q: "What is 62% of 50?", a: "31" },
      { n: 27, topic: "Discount", q: "A $95 bike is marked down 20%. What is the sale price in dollars?", a: "76" },
      { n: 28, topic: "Find the whole", q: "5% of what number is 7?", a: "140" },
      { n: 29, topic: "Tax", q: "A book costs $15 plus 6% sales tax. What is the total cost in dollars?", a: "15.90" },
      { n: 30, topic: "Find the whole", q: "A jacket sells for $56 after a 30% discount. What was the original price in dollars?", a: "80" },
    ],
  },
  {
    key: "inequalities",
    label: "Inequalities",
    questions: [
      { n: 1, topic: "Solve add", q: "Solve: x + 7 < 15", a: "x < 8" },
      { n: 2, topic: "At least", q: "You must be at least 48 inches tall to ride the coaster. Write an inequality for a rider's height h.", a: "h >= 48" },
      { n: 3, topic: "Solve multiply", q: "Solve: 5x <= 45", a: "x <= 9" },
      { n: 4, topic: "Solution check", q: "Is 6 a solution of 3x < 20? Answer yes or no.", a: "yes" },
      { n: 5, topic: "At most", q: "A backpack can hold at most 25 pounds. Write an inequality for the weight w it can hold.", a: "w <= 25" },
      { n: 6, topic: "Solve subtract", q: "Solve: n - 4 >= 9", a: "n >= 13" },
      { n: 7, topic: "Solve divide", q: "Solve: y/3 > 6", a: "y > 18" },
      { n: 8, topic: "Word problem", q: "Tickets cost 8 dollars each and Leo has 50 dollars. Solve 8t <= 50. How many whole tickets can he buy?", a: "6" },
      { n: 9, topic: "Reversed form", q: "Solve: 12 <= x + 5", a: "x >= 7" },
      { n: 10, topic: "More than", q: "Kids more than 5 years old pay full price at the fair. Write an inequality for those ages a.", a: "a > 5" },
      { n: 11, topic: "Solve multiply", q: "Solve: 8n >= 56", a: "n >= 7" },
      { n: 12, topic: "Solution check", q: "Is 9 a solution of x - 4 >= 6? Answer yes or no.", a: "no" },
      { n: 13, topic: "Word problem", q: "Mia has 62 points and needs at least 90 to win. Solve p + 62 >= 90 for the points p she still needs.", a: "p >= 28" },
      { n: 14, topic: "Solve decimals", q: "Solve: x + 3.5 <= 10", a: "x <= 6.5" },
      { n: 15, topic: "Solve add", q: "Solve: m + 9 > 21", a: "m > 12" },
      { n: 16, topic: "Fewer than", q: "Fewer than 30 students signed up for chess club. Write an inequality for the number of students s.", a: "s < 30" },
      { n: 17, topic: "Solve divide", q: "Solve: w/5 <= 4", a: "w <= 20" },
      { n: 18, topic: "Word problem", q: "Jon saves 12 dollars each week and wants at least 96 dollars. Solve 12w >= 96 for the weeks w.", a: "w >= 8" },
      { n: 19, topic: "Solve decimals", q: "Solve: 4y < 22", a: "y < 5.5" },
      { n: 20, topic: "Solution check", q: "Is 12 a solution of x/4 <= 3? Answer yes or no.", a: "yes" },
      { n: 21, topic: "At most", q: "A recipe uses no more than 3/4 cup of sugar. Write an inequality for the sugar s in cups.", a: "s <= 3/4" },
      { n: 22, topic: "Solve subtract", q: "Solve: k - 15 < 6", a: "k < 21" },
      { n: 23, topic: "Less than", q: "The freezer must stay below 32 degrees. Write an inequality for its temperature t.", a: "t < 32" },
      { n: 24, topic: "Reversed form", q: "Solve: 30 > 6m", a: "m < 5" },
      { n: 25, topic: "Word problem", q: "An elevator holds at most 1500 pounds. Solve 10c <= 1500 for the weight c of each of 10 equal crates.", a: "c <= 150" },
      { n: 26, topic: "Solve divide", q: "Solve: n/2 >= 4.5", a: "n >= 9" },
      { n: 27, topic: "Solution check", q: "A ride requires height h >= 54. Priya is 52 inches tall. Can she ride? Answer yes or no.", a: "no" },
      { n: 28, topic: "Solve decimals", q: "Solve: x - 2.5 > 7", a: "x > 9.5" },
      { n: 29, topic: "Word problem", q: "Vans hold 9 kids each. At least 40 kids are going. Solve 9v >= 40. How many vans are needed?", a: "5" },
      { n: 30, topic: "Solve fractions", q: "Solve: y/4 > 1/2", a: "y > 2" },
    ],
  },
  {
    key: "geometry",
    label: "Area & Perimeter",
    questions: [
      { n: 1, topic: "Rectangle area", q: "What is the area of a rectangle with length 12 cm and width 7 cm?", a: "84" },
      { n: 2, topic: "Triangle area", q: "A triangle has a base of 10 in and a height of 9 in. What is its area?", a: "45" },
      { n: 3, topic: "Fencing", q: "A garden is 18 ft long and 11 ft wide. How many feet of fencing are needed to go all the way around?", a: "58" },
      { n: 4, topic: "Parallelogram area", q: "Find the area of a parallelogram with base 9 ft and height 8 ft.", a: "72" },
      { n: 5, topic: "Perimeter", q: "What is the perimeter of a rectangle with length 15 m and width 9 m?", a: "48" },
      { n: 6, topic: "Carpet area", q: "A bedroom floor is 15 ft by 12 ft. How many square feet of carpet are needed to cover the whole floor?", a: "180" },
      { n: 7, topic: "Missing width", q: "A rectangle has an area of 96 sq cm and a length of 12 cm. What is its width?", a: "8" },
      { n: 8, topic: "Decimal area", q: "Find the area of a rectangle that is 8.5 m long and 4 m wide.", a: "34" },
      { n: 9, topic: "Sail area", q: "A triangular sail has a base of 8 ft and a height of 12 ft. What is the area of the sail?", a: "48" },
      { n: 10, topic: "Triangle height", q: "A triangle has an area of 30 sq ft and a base of 12 ft. What is its height?", a: "5" },
      { n: 11, topic: "Square perimeter", q: "What is the perimeter of a square with side length 13 cm?", a: "52" },
      { n: 12, topic: "Banner width", q: "A rectangular banner has an area of 54 sq ft. If it is 9 ft long, how wide is it?", a: "6" },
      { n: 13, topic: "Parallelogram area", q: "What is the area of a parallelogram with base 7.5 cm and height 4 cm?", a: "30" },
      { n: 14, topic: "Decimal perimeter", q: "Find the perimeter of a rectangle that is 6.5 in long and 3.5 in wide.", a: "20" },
      { n: 15, topic: "Patio area", q: "A patio shaped like a parallelogram has a base of 11 m and a height of 6 m. What is its area?", a: "66" },
      { n: 16, topic: "Missing height", q: "A parallelogram has an area of 63 sq m and a base of 9 m. What is its height?", a: "7" },
      { n: 17, topic: "Fraction area", q: "What is the area of a rectangle with length 8 in and width 3/4 in?", a: "6" },
      { n: 18, topic: "Fence cost", q: "Fence costs $4 per foot. What is the total cost, in dollars, to fence a yard 20 ft long and 15 ft wide?", a: "280" },
      { n: 19, topic: "Triangle area", q: "What is the area of a triangle with base 16 cm and height 11 cm?", a: "88" },
      { n: 20, topic: "Square", q: "A square has an area of 81 sq ft. What is its perimeter in feet?", a: "36" },
      { n: 21, topic: "Tiling", q: "Square tiles measure 1 ft on each side. How many tiles are needed to cover a floor that is 9 ft by 7 ft?", a: "63" },
      { n: 22, topic: "Perimeter missing", q: "A rectangle has a perimeter of 46 in and a length of 14 in. What is its width?", a: "9" },
      { n: 23, topic: "Decimal triangle", q: "Find the area of a triangle with base 5 m and height 4.5 m.", a: "11.25" },
      { n: 24, topic: "Poster area", q: "A poster is 2.5 ft wide and 4 ft tall. What is its area in square feet?", a: "10" },
      { n: 25, topic: "Parallelogram", q: "A parallelogram has a base of 12.5 ft and a height of 8 ft. Find its area.", a: "100" },
      { n: 26, topic: "Missing base", q: "A triangle has an area of 28 sq in and a height of 8 in. What is its base?", a: "7" },
      { n: 27, topic: "Flag height", q: "A triangular flag has an area of 24 sq in and a base of 6 in. What is its height?", a: "8" },
      { n: 28, topic: "Wall area", q: "A wall is 14 ft wide and 9 ft tall. What is the area of the wall in square feet?", a: "126" },
      { n: 29, topic: "Laps", q: "Dana runs 3 laps around a rectangular field that is 90 m long and 60 m wide. How many meters is that in all?", a: "900" },
      { n: 30, topic: "Garden area", q: "A triangular garden plot has a base of 9 m and a height of 7 m. What is its area in square meters?", a: "31.5" },
    ],
  },
  {
    key: "orderofops",
    label: "Order of Operations",
    questions: [
      { n: 1, topic: "Two-step", q: "Evaluate: 8 + 4 * 3", a: "20" },
      { n: 2, topic: "Grouping first", q: "Evaluate: (8 + 4) * 3", a: "36" },
      { n: 3, topic: "Exponents", q: "Evaluate: 5 + 2^3", a: "13" },
      { n: 4, topic: "Word problem", q: "Movie tickets cost 8 dollars each. Jaden pays for 3 tickets with 30 dollars. How much change does he get?", a: "6" },
      { n: 5, topic: "Mixed operations", q: "Evaluate: 24 / 6 + 2 * 5", a: "14" },
      { n: 6, topic: "Left to right", q: "Evaluate: 36 / 4 * 3", a: "27" },
      { n: 7, topic: "Word problem", q: "A trip uses 5 vans with 6 students each and 2 cars with 4 students each. How many students in all?", a: "38" },
      { n: 8, topic: "Left to right", q: "Evaluate: 20 - 8 + 5", a: "17" },
      { n: 9, topic: "Grouping and exponent", q: "Evaluate: (10 - 6)^3", a: "64" },
      { n: 10, topic: "Word problem", q: "A recipe uses 2 cups of flour per batch. Ana makes 4 batches, then uses 3 more cups for bread. Total cups?", a: "11" },
      { n: 11, topic: "Nested grouping", q: "Evaluate: 2 * [10 - (3 + 4)]", a: "6" },
      { n: 12, topic: "Grouping first", q: "Evaluate: (18 + 6) / 8", a: "3" },
      { n: 13, topic: "Word problem", q: "Sam has 50 dollars, buys 4 books at 8 dollars each, then splits what is left with a friend. How much each?", a: "9" },
      { n: 14, topic: "Exponents", q: "Evaluate: 4 * 2^3 - 5", a: "27" },
      { n: 15, topic: "Exponents", q: "Evaluate: 100 - 5^2 * 3", a: "25" },
      { n: 16, topic: "Word problem", q: "A square patio has side length 6 feet. A garden bed adds 24 more square feet. What is the total area?", a: "60" },
      { n: 17, topic: "Grouping and exponent", q: "Evaluate: (5 + 3)^2 / 4", a: "16" },
      { n: 18, topic: "Grouping first", q: "Evaluate: 9 + 3 * (12 - 7)", a: "24" },
      { n: 19, topic: "Word problem", q: "Three friends split the cost of 2 pizzas at 9 dollars each plus a 6 dollar salad. How much does each pay?", a: "8" },
      { n: 20, topic: "Exponents", q: "Evaluate: 2^4 - 3 * 4", a: "4" },
      { n: 21, topic: "Left to right", q: "Evaluate: 48 / (2 + 6) * 5", a: "30" },
      { n: 22, topic: "Word problem", q: "Lena reads 15 pages a day for 4 days, then 20 pages on Friday. How many pages does she read in all?", a: "80" },
      { n: 23, topic: "Decimals", q: "Evaluate: 3.5 + 2 * 1.5", a: "6.5" },
      { n: 24, topic: "Exponents", q: "Evaluate: 10^2 / (14 - 9)", a: "20" },
      { n: 25, topic: "Word problem", q: "T-shirts cost 12 dollars each. A coupon takes 2 dollars off each shirt. What do 5 shirts cost?", a: "50" },
      { n: 26, topic: "Exponents", q: "Evaluate: 3^2 * 5", a: "45" },
      { n: 27, topic: "Word problem", q: "A club sells 9 boxes of candy at 4 dollars each and spends 15 dollars on supplies. What is the profit?", a: "21" },
      { n: 28, topic: "Error analysis", q: "Kai says 7 + 3 * 4 = 40. What is the correct value of the expression?", a: "19" },
      { n: 29, topic: "Insert grouping", q: "Add one pair of parentheses to make this true: 3 + 5 * 2 = 16", a: "(3 + 5) * 2" },
      { n: 30, topic: "True or false", q: "True or false: 18 - 6 / 3 equals 4", a: "false" },
    ],
  },
];

export function presetByKey(key: string): BruhPreset | null {
  return BRUH_PRESETS.find((p) => p.key === key) ?? null;
}
